# https://beta.developer.spotify.com/dashboard/applications

CLIENT_ID = "YOUR KEY ID HERE"
CLIENT_SECRET = "YOUR SECRET HERE"
SPOTIFY_USER_ID = "SPOTIFY USER ID HERE"
SPOTIFY_PLAYLIST_ID = "SPOTIFY PLAYLIST ID HERE"

test
